name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false
  - type: dropdown
    id: repo
    attributes:
      label: Related repository
      options:
        - shepard-obs-stack (The Eye)
        - shepard-core (The Staff)
        - shepard-knwl-lake (The Pasture)
        - shepard-mcp-hub (The Gate)
        - shepard-mem-layer (The Memory)
        - Not sure / multiple
    validations:
      required: true
